### ISSUE TITLE
Android: more color options

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium-web-dialog#176]
While updating to the new library I saw that it is possible to set different colors too:

* setNavigationBarColor
* setNavigationBarDividerColor
* setToolbarColor 
* setSecondaryToolbarColor

currently the module only uses the bar color (`setToolbarColor`).

**How to add it:**
* add a new parameter https://github.com/appcelerator-modules/titanium-web-dialog/blob/master/android/src/ti/webdialog/Params.java
* extend [the builder](https://github.com/appcelerator-modules/titanium-web-dialog/blob/2212b0955c2a8cadff96ea6d23a604dd7bc73521/android/src/ti/webdialog/TitaniumWebDialogModule.java#L68-L74) with the parameter and the correct method
* update the version number in the manifest file
* build and test the module `ti build -p android -b`
* to format the code: `npm i && npm format:android`
* add paramter to [the documentation](https://github.com/appcelerator-modules/titanium-web-dialog/blob/master/apidoc/WebDialog.yml)

**Comment by hansemannn** [comment]
Fixed as part of #175
