### ISSUE TITLE
iOS: Crash using some links

### ISSUE THREAD

**Issue by macasfaj** [tidev/titanium-web-dialog#33]
I'm using the last release, 2.0.0. If I try to open this link, the app is finished. I'm using SKD 9.0.3GA and CLI 8.0.0

https://www.apple.com/apple-events/?&mnid=sHJMYwTXV-dc_mtid_20925ni039944_pcrid_462922814791_pgrid_111466383591_&mtid=20925ni039944&aosid=p238&cid=wwa-es-kwgo-features-%7Bcid_seasonal%7D-slid---productid----Post-&anonymizeip=set

Thanks

**Comment by hansemannn** [comment]
Should be fixed in v3.0.2 (just released)! :)
